param(
  [string]$ProjectId = "omnicrystal",
  [Parameter(Mandatory = $true)]
  [string]$AdapterBaseUrl,
  [Parameter(Mandatory = $true)]
  [string]$WorldSimApiKey,
  [string]$LlmProvider = "openrouter",
  [string]$LlmBaseUrl = "https://openrouter.ai/api/v1",
  [string]$LlmApiKey = "",
  [string]$LlmModelQuery = "openai/gpt-4.1-mini",
  [string]$LlmModelForecast = "openai/gpt-4.1-mini",
  [string]$LlmModelChat = "openai/gpt-4.1-mini",
  [string]$LlmModelCopy = "openai/gpt-4.1-mini",
  [string]$SportsProvider = "api-football",
  [string]$SportsProviderBaseUrl = "https://v3.football.api-sports.io",
  [string]$SportsApiKey = "",
  [switch]$BillingTestMode,
  [switch]$SkipFunctions,
  [switch]$SkipFirestore,
  [switch]$SkipHosting
)

$ErrorActionPreference = "Stop"

function Invoke-FirebaseCli {
  param(
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$Args
  )

  $command = "npx firebase-tools $($Args -join ' ')"
  & cmd.exe /c $command
  if ($LASTEXITCODE -ne 0) {
    throw "Firebase CLI command failed: firebase-tools $($Args -join ' ')"
  }
}

function Test-FirebaseSecret {
  param(
    [string]$Name
  )

  $tmpPrefix = Join-Path $env:TEMP ("crystal-secret-check-" + [Guid]::NewGuid().ToString("N"))
  $stdout = "$tmpPrefix.out"
  $stderr = "$tmpPrefix.err"

  try {
    $proc = Start-Process `
      -FilePath "cmd.exe" `
      -ArgumentList "/c", "npx firebase-tools functions:secrets:access $Name --project $ProjectId" `
      -NoNewWindow `
      -RedirectStandardOutput $stdout `
      -RedirectStandardError $stderr `
      -Wait `
      -PassThru

    return $proc.ExitCode -eq 0
  } finally {
    Remove-Item $stdout, $stderr -Force -ErrorAction SilentlyContinue
  }
}

$requiredSecrets = @(
  "GEMINI_API_KEY",
  "NIXTLA_API_KEY",
  "STRIPE_SECRET_KEY",
  "STRIPE_WEBHOOK_SECRET"
)

$missingSecrets = @($requiredSecrets | Where-Object { -not (Test-FirebaseSecret -Name $_) })
if ($missingSecrets.Count -gt 0) {
  throw "Missing Firebase Function secrets: $($missingSecrets -join ', '). Set them before deploying functions."
}

$repoRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path))
$functionsEnvPath = Join-Path $repoRoot "functions\.env.$ProjectId"
$adapterUrl = $AdapterBaseUrl.TrimEnd("/")

if ([string]::IsNullOrWhiteSpace($LlmApiKey)) {
  throw "Missing LlmApiKey. Pass the OpenRouter key so Firebase Functions can enable forecast generation."
}

$envContent = @(
  "# Generated by infra/mirofish/deploy-firebase.ps1"
  "MIROFISH_BASE_URL=$adapterUrl"
  "MIROFISH_API_KEY=$WorldSimApiKey"
  ""
  "WORLDSIM_BASE_URL=$adapterUrl"
  "WORLDSIM_API_KEY=$WorldSimApiKey"
  ""
  "LLM_PROVIDER=$LlmProvider"
  "LLM_BASE_URL=$LlmBaseUrl"
  "LLM_API_KEY=$LlmApiKey"
  "LLM_MODEL_QUERY=$LlmModelQuery"
  "LLM_MODEL_FORECAST=$LlmModelForecast"
  "LLM_MODEL_CHAT=$LlmModelChat"
  "LLM_MODEL_COPY=$LlmModelCopy"
  "SPORTS_PROVIDER=$SportsProvider"
  "SPORTS_PROVIDER_BASE_URL=$SportsProviderBaseUrl"
  "API_FOOTBALL_KEY=$SportsApiKey"
  ""
  "BILLING_TEST_MODE=$($BillingTestMode.IsPresent.ToString().ToLower())"
)

Set-Content -Path $functionsEnvPath -Value $envContent -Encoding UTF8
Write-Host "Functions env file updated: $functionsEnvPath"

if (-not $SkipFunctions) {
  Write-Host "Deploying Firebase Functions..."
  Invoke-FirebaseCli deploy --only functions:api --project $ProjectId --force
}

if (-not $SkipFirestore) {
  Write-Host "Deploying Firestore rules..."
  Invoke-FirebaseCli deploy --only firestore:rules --project $ProjectId
}

if (-not $SkipHosting) {
  Write-Host "Deploying Hosting..."
  Invoke-FirebaseCli deploy --only hosting --project $ProjectId
}

Write-Host ""
Write-Host "Firebase deploy flow completed."
Write-Host "Project: $ProjectId"
Write-Host "Adapter URL: $adapterUrl"
